idam_api_base_uri = "http://idam-api-idam-sprod.service.core-compute-idam-sprod.internal"
docmosis_uri = "https://docmosis-testing.platform.hmcts.net/rs/render"
docmosis_templates_uri = "https://docmosis-testing.platform.hmcts.net"
capacity = "2"
dns_server="10.100.11.254"
